name: nightly build

on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Building
        run:
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -o gomcp-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: gomcp-${{ matrix.os }}-${{ matrix.arch }}
